-- MySQL Script generated by MySQL Workbench
-- Mon Aug 31 19:12:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_proyecto_tecnologo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_proyecto_tecnologo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_proyecto_tecnologo` DEFAULT CHARACTER SET utf8 ;
USE `db_proyecto_tecnologo` ;

-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`EDITORIALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`EDITORIALES` (
  `editorial_id` INT NOT NULL AUTO_INCREMENT,
  `editorial_nombre` VARCHAR(100) NOT NULL,
  `editorial_direccion` VARCHAR(100) NOT NULL,
  `editorial_telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`editorial_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`LIBROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`LIBROS` (
  `editorial_id` INT NOT NULL COMMENT 'Identificador de Editorial',
  `libro_categoria` VARCHAR(100) NOT NULL COMMENT 'Llave Foránea de la Categoría',
  `libro_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador del Libro',
  `libro_titulo` VARCHAR(100) NOT NULL COMMENT 'Título del Libro',
  `libro_idioma` VARCHAR(100) NOT NULL COMMENT 'Idioma del Libro',
  `libro_formato` VARCHAR(50) NOT NULL COMMENT 'Formato del Libro (Digital, Impreso)',
  PRIMARY KEY (`libro_id`),
  INDEX `fi_libro_editorial_idx` (`editorial_id` ASC),
  CONSTRAINT `fi_libro_editorial`
    FOREIGN KEY (`editorial_id`)
    REFERENCES `db_proyecto_tecnologo`.`EDITORIALES` (`editorial_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`TEMAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`TEMAS` (
  `tema_id` INT NOT NULL AUTO_INCREMENT,
  `tema_nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`tema_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`AUTORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`AUTORES` (
  `autor_id` INT NOT NULL AUTO_INCREMENT,
  `autor_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`autor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`SOCIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`SOCIOS` (
  `socio_categoria` VARCHAR(100) NOT NULL,
  `socio_id` INT NOT NULL AUTO_INCREMENT,
  `socio_nombre` VARCHAR(100) NOT NULL,
  `socio_direccion` VARCHAR(100) NOT NULL,
  `socio_telefono` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`socio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`EJEMPLARES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`EJEMPLARES` (
  `libro_id` INT NOT NULL,
  `ejemplar_id` INT NOT NULL,
  `ejemplar_num_orden` INT(10) NOT NULL,
  `ejemplar_edicion` VARCHAR(45) NOT NULL,
  `ejemplar_ubicacion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ejemplar_id`),
  INDEX `fk_editorial_libro_idx` (`libro_id` ASC),
  CONSTRAINT `fk_editorial_libro`
    FOREIGN KEY (`libro_id`)
    REFERENCES `db_proyecto_tecnologo`.`LIBROS` (`libro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`TRATA_SOBRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`TRATA_SOBRE` (
  `libro_id` INT NOT NULL,
  `tema_id` INT NOT NULL,
  INDEX `ind_trata_sobre_libros` (`libro_id` ASC),
  INDEX `ind_trata_sobre_temas` (`tema_id` ASC),
  CONSTRAINT `fk_trata_sobre_libros`
    FOREIGN KEY (`libro_id`)
    REFERENCES `db_proyecto_tecnologo`.`LIBROS` (`libro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_trata_sobre_temas`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_proyecto_tecnologo`.`TEMAS` (`tema_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`ESCRITO_POR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`ESCRITO_POR` (
  `libros_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  INDEX `ind_escrito_por_libros` (`libros_id` ASC),
  INDEX `ind_escrito_por_autor` (`autor_id` ASC),
  CONSTRAINT `fk_escrito_por_libros`
    FOREIGN KEY (`libros_id`)
    REFERENCES `db_proyecto_tecnologo`.`LIBROS` (`libro_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_escrito_por_autor`
    FOREIGN KEY (`autor_id`)
    REFERENCES `db_proyecto_tecnologo`.`AUTORES` (`autor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto_tecnologo`.`PRESTAMOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto_tecnologo`.`PRESTAMOS` (
  `socio_id` INT NOT NULL,
  `ejemplar_id` INT NOT NULL,
  `prestamo_fecha_solictud` DATE NOT NULL,
  `prestamo_fecha_devolucion` DATE NOT NULL,
  `prestamo_notas` VARCHAR(300) NOT NULL,
  INDEX `fk_prestamo_socio_idx` (`socio_id` ASC),
  INDEX `fk_prestamo_ejemplar_idx` (`ejemplar_id` ASC),
  CONSTRAINT `fk_prestamo_socio`
    FOREIGN KEY (`socio_id`)
    REFERENCES `db_proyecto_tecnologo`.`SOCIOS` (`socio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prestamo_ejemplar`
    FOREIGN KEY (`ejemplar_id`)
    REFERENCES `db_proyecto_tecnologo`.`EJEMPLARES` (`ejemplar_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
